mc.azure.control.panel/Controllers/SqlServerFirewallRulesController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

using JetBrains.Annotations;

using mc.azure.sdk.wrappers.Interfaces;
using mc.azure.sdk.wrappers.Models;

namespace mc.azure.controlpanel.Controllers {
#if !DEBUG
    [Authorize]
#endif
    public class SqlServerFirewallRulesController : Controller {
        private readonly string ipRuleErrorKey = "IpRuleError";
        private readonly IAzureResourceService azureResourceService;

        //---------------------------------------------------------------------

        public SqlServerFirewallRulesController([NotNull] IAzureResourceService azureResourceService) {
            this.azureResourceService =
                azureResourceService ?? throw new ArgumentNullException(nameof(azureResourceService));
        }

        //---------------------------------------------------------------------

        // GET: ManageIps
        public async Task<ActionResult> Index() {
            var firewallRules = await azureResourceService.GetFirewallRulesAsync();
            var model = new FirewallRuleCollectionModel {
                ExistingFirewallRules = firewallRules,
                CurrentClientIp = Request.UserHostAddress,
                Feedback = (string)TempData[ipRuleErrorKey]
            };
            return View(model);
        }

        //---------------------------------------------------------------------

        [HttpPost]
        public async Task<ActionResult> AddFirewallRule(FirewallRuleCollectionModel model) {
            await azureResourceService.AddFirewallRuleForIpAsync(model);
            TempData[ipRuleErrorKey] = azureResourceService.Feedback;

            // TODO - error handling!

            return RedirectToAction("Index");
        }

        //---------------------------------------------------------------------
    }
}

mc.azure.control.panel/Views/SqlServerFirewallRules/Index.cshtml
@using System.Diagnostics
@model mc.azure.sdk.wrappers.Models.FirewallRuleCollectionModel

@{
    ViewBag.Title = "Index";
}

<h2>Current Sql Server Firewall Rules</h2>


@if (Debugger.IsAttached) {
    <p>Not available in Debug mode!</p>
    return;
}


<h3>Client IP: @Model.CurrentClientIp</h3>


<table class="table">
    <thead>
    <tr>
        <th>SqlServerName</th>
        <th>Kind</th>
        <th>StartIpAddress</th>
        <th>EndIpAddress</th>
        <th>Region</th>
    </tr>
    </thead>
    @foreach (var firewallRule in Model.ExistingFirewallRules) {
        <tr>
            <td>
                @Html.DisplayFor(model => firewallRule.SqlServerName)
            </td>
            <td>
                @Html.DisplayFor(model => firewallRule.Kind)
            </td>
            <td>
                @Html.DisplayFor(model => firewallRule.StartIpAddress)
            </td>
            <td>
                @Html.DisplayFor(model => firewallRule.EndIpAddress)
            </td>
            <td>
                @Html.DisplayFor(model => firewallRule.Region)
            </td>

        </tr>
    }


</table>


@if (!string.IsNullOrWhiteSpace(Model.Feedback)) {
    <div class="row">
        <div class="col-md-2">
            <div class="form-group">
                @Html.LabelFor(m => m.Feedback)
            </div>
        </div><!-- /.col -->
        <div class="col-md-10">
            @*<div class="form-group">
                    @Html.TextAreaFor(m => m.Feedback, new { height = 20, @readonly = "readonly" })
                </div>*@
            @* TODO - improve this!! *@
            <label style="color: red">@Model.Feedback</label>
        </div><!-- /.col -->
    </div>
}


@using (Html.BeginForm("AddFirewallRule", "SqlServerFirewallRules")) {
    <div class="row">
        <div class="col-md-2">
            <div class="form-group">
                @Html.LabelFor(m => m.NewRuleName)
            </div>
        </div><!-- /.col -->

        <div class="col-md-2">
            <div class="form-group">
                @Html.TextBoxFor(m => m.NewRuleName, new {required = "required", placeholder = "Rule name"})
            </div>
        </div><!-- /.col -->

        <div class="col-md-2">
            <div class="form-group">
                @Html.LabelFor(m => m.NewRuleIp)
            </div>
        </div><!-- /.col -->

        <div class="col-md-2">
            <div class="form-group">
                @Html.TextBoxFor(m => m.NewRuleIp, new {Value = Model.CurrentClientIp, required = "required"})
            </div>
        </div><!-- /.col -->

        <div class="col-md-2">
            <button type="submit" class="btn btn-primary">Add IP rule</button>
        </div>

    </div>
    <!-- /.row -->
}