mc.azure.control.panel/Controllers/CreateCustomerController.cs
using System;
using System.Text;
using System.Web.Mvc;

using Hangfire;

using JetBrains.Annotations;

using mc.azure.sdk.wrappers.Interfaces;
using mc.azure.sdk.wrappers.Models;
using mc.azure.utilities.IO;

namespace mc.azure.controlpanel.Controllers {
#if !DEBUG
    [Authorize]
#endif
    public class CreateCustomerController : Controller {
        private readonly string basicCustomerKey = "basicCustomerInfo";

        private readonly IAzureResourceService azureResourceService;

        //---------------------------------------------------------------------

        public CreateCustomerController([NotNull] IAzureResourceService azureResourceService) {
            this.azureResourceService =
                azureResourceService ?? throw new ArgumentNullException(nameof(azureResourceService));
        }

        //---------------------------------------------------------------------

        [HttpGet]
        public ActionResult Index() {
            return View(getBasicCustomerModel());
        }

        //---------------------------------------------------------------------

        [HttpPost]
        public ActionResult Index(BasicCustomerModel model) {
            if (!ModelState.IsValid) {
                return View(model);
            }

            if (!canCreateCustomerInfrastructure(model, out var actionResult)) {
                return actionResult;
            }

            updateBasicCustomerModel(model);

            return RedirectToAction("Confirm");
        }

        //---------------------------------------------------------------------

        [HttpGet]
        public ActionResult Confirm() {
            var basicCustomerInfo = getBasicCustomerModel();

            if (string.IsNullOrWhiteSpace(basicCustomerInfo.Name)) {
                return RedirectToAction("Index");
            }

            var createCustomerInfo = new CustomerCreateModel(basicCustomerInfo);

            createCustomerInfo.IsNewCustomer = azureResourceService.IsNewCustomer(createCustomerInfo);

            if (!createCustomerInfo.IsNewCustomer) {
                createCustomerInfo.DbBackupAvailable =
                    azureResourceService.IsCustomerDbBackupAvailable(createCustomerInfo);
            }

            return View(createCustomerInfo);
        }

        //---------------------------------------------------------------------

        [HttpPost]
        public ActionResult Confirm(CustomerCreateModel model) {
            if (!ModelState.IsValid) {
                return View(model);
            }

            if (!canCreateCustomerInfrastructure(model, out var actionResult)) {
                return actionResult;
            }

            var sitePath = DirectoryUtils.GetSiteDir(System.Web.HttpContext.Current.Server.MapPath("/"));
            BackgroundJob.Enqueue<IAzureResourceService>(
                x => x.CreateCustomerAsync(model, sitePath, System.Web.HttpContext.Current.Request.UserHostAddress));

            StringBuilder sb = new StringBuilder();
            sb.AppendLine($"Creating resources for customer '{model.CustomerFullName}'.");

            sb.AppendLine(
                model.SupportEmailRecipients == null
                    ? "No support email address was provided.  You can go to 'View client info' to track the progress of your request."
                    : $"An email will be sent to '{model.SupportEmailRecipients}' to notify you of the outcome.");

            removeBasicCustomerModel();

            return RedirectToAction("Index", "Feedback", new {message = sb.ToString()});
        }

        //---------------------------------------------------------------------

        private bool canCreateCustomerInfrastructure(BasicCustomerModel model, out ActionResult redirect) {
            var customerCreateInfo = new CustomerCreateModel(model);
            return canCreateCustomerInfrastructure(customerCreateInfo, out redirect);
        }

        //---------------------------------------------------------------------

        private bool canCreateCustomerInfrastructure(CustomerCreateModel model, out ActionResult redirect) {
            if (azureResourceService.CanCreateCustomerInfrastructure(model, out var message)) {
                redirect = null;
                return true;
            }

            removeBasicCustomerModel();

            var errorMsg = $"Cannot create infrastructure for customer '{model.CustomerFullName}'."
                           + $"{Environment.NewLine}"
                           + $"Reason:  {message}";

            redirect = RedirectToAction("Index", "Feedback", new {message = errorMsg});
            return false;
        }

        //---------------------------------------------------------------------

        private BasicCustomerModel getBasicCustomerModel() {
            if (Session[basicCustomerKey] == null) {
                Session[basicCustomerKey] = new BasicCustomerModel();
            }

            return (BasicCustomerModel)Session[basicCustomerKey];
        }

        //---------------------------------------------------------------------

        private void updateBasicCustomerModel(BasicCustomerModel model) {
            // TODO - is this safe?
            // is there some condition to test for before updating?
            Session[basicCustomerKey] = model;
        }

        //---------------------------------------------------------------------

        private void removeBasicCustomerModel() {
            Session.Remove(basicCustomerKey);
        }

        //---------------------------------------------------------------------
    }
}

mc.azure.control.panel/Views/CreateCustomer/Confirm.cshtml
@model mc.azure.sdk.wrappers.Models.CustomerCreateModel

@{
    ViewBag.Title = "Confirm";
}

<h2>Confirm</h2>


@Html.HiddenFor(m => m.CustomerNameLocation.Name)
@Html.HiddenFor(m => m.CustomerNameLocation.Location)
@Html.HiddenFor(m => m.DbBackupAvailable)
@Html.HiddenFor(m => m.IsNewCustomer)



@using (Html.BeginForm("Confirm", "CreateCustomer")) {
    @Html.ValidationSummary(false, "Please provide the required information before submitting!", new {@class = "text-danger"})

    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(m => m.IsNewCustomer)
            </div>
        </div><!-- /.col -->

        <div class="col-md-8">
            <div class="form-group">
                @if (Model.IsNewCustomer) {
                    <b>Yes</b>
                }
                else {
                    <b>No</b>
                }
            </div>
        </div><!-- /.col -->
    </div>
    <!-- /.row -->

    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(m => m.CustomerNameLocation.Name)
            </div>
        </div><!-- /.col -->

        <div class="col-md-8">
            <div class="form-group">
                @Html.TextBoxFor(m => m.CustomerNameLocation.Name, new {@readonly = "readonly"})
                <br/>
                @Html.ValidationMessageFor(m => m.CustomerNameLocation.Name, "", new {@class = "text-danger"})
            </div>
        </div><!-- /.col -->
    </div>
    <!-- /.row -->

    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(m => m.CustomerNameLocation.Location)
            </div>
        </div><!-- /.col -->

        <div class="col-md-8">
            <div class="form-group">
                @Html.TextBoxFor(m => m.CustomerNameLocation.Location, new {@readonly = "readonly"})
            </div>
        </div><!-- /.col -->
    </div>
    <!-- /.row -->

    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(m => m.EmailRecipients)
            </div>
        </div><!-- /.col -->

        <div class="col-md-8">
            <div class="form-group">
                @Html.TextBoxFor(m => m.EmailRecipients)
            </div>
        </div><!-- /.col -->
    </div>
    <!-- /.row -->

    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(m => m.SupportEmailRecipients)
            </div>
        </div><!-- /.col -->

        <div class="col-md-8">
            <div class="form-group">
                @Html.TextBoxFor(m => m.SupportEmailRecipients, new {required = "required"})
                <br/>
                @Html.ValidationMessageFor(m => m.SupportEmailRecipients, "", new {@class = "text-danger"})
            </div>
        </div><!-- /.col -->
    </div>
    <!-- /.row -->

    if (Model.DbBackupAvailable) {
        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    @Html.LabelFor(m => m.ShouldRecoverDbFromBackup)
                </div>
            </div><!-- /.col -->

            <div class="col-md-6">
                <div class="form-group">
                    @Html.CheckBoxFor(m => m.ShouldRecoverDbFromBackup)
                </div>
            </div><!-- /.col -->
        </div>
        <!-- /.row -->
    }

    <div>
        <button type="submit" class="btn btn-primary">Ok</button>
    </div>
} 

mc.azure.control.panel/Views/CreateCustomer/Index.cshtml
@model mc.azure.sdk.wrappers.Models.BasicCustomerModel

@{
    ViewBag.Title = "Create Customer";
}

<h2>Create Customer</h2>


@using (Html.BeginForm("Index", "CreateCustomer")) {
    @Html.ValidationSummary(false, "Please provide the required information before submitting!", new {@class = "text-danger"})

    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(m => m.Name)
            </div>
        </div><!-- /.col -->

        <div class="col-md-8">
            <div class="form-group">
                @Html.TextBoxFor(m => m.Name, new {required = "required", pattern = @"^([a-zA-Z0-9 ]+)$", title = "Only use alphanumeric characters."})
                <br/>
                @Html.ValidationMessageFor(m => m.Name, "", new {@class = "text-danger"})
            </div>
            <span asp-validation-for="Title" class="text-danger"></span>
        </div><!-- /.col -->
    </div>
    <!-- /.row -->

    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(m => m.Location)
            </div>
        </div><!-- /.col -->

        <div class="col-md-8">
            <div class="form-group">
                @Html.TextBoxFor(m => m.Location, new {
                    pattern = @"^([a-zA-Z0-9 ]+)$",
                    title = "Only use alphanumeric characters."
                })
            </div>
        </div><!-- /.col -->
    </div>
    <!-- /.row -->

    <div>
        <button type="submit" class="btn btn-primary">Ok</button>
    </div>
} 